### ISSUE TITLE
is there any known injection latency issue with having circular dependencies?

### ISSUE THREAD

**Issue by venkatesh3007** [kejunxia/AndroidMvc#46]
For ex : -

I have ControllerA & ControllerB in my application. ControllerA has ControllerB injected in it and ControllerB has ControllerB injected as in it.

Do you think that this can be the cause of delay in dependencies getting injected and as a result delaying the transition from one fragment to another?

**Comment by kejunxia** [comment]
The injector should be able to detect circular injection. Once it detects circular injection, it would stop. Otherwise it will fall to infinite loop. There are some test cases here
https://github.com/kejunxia/AndroidMvc/blob/master/library/poke/src/test/java/com/shipdream/lib/poke/TestCircularDependencies.java

When you say delay, do you feel the fragments are loaded slowly, or you met some race conditions that for example you called something before they are injected? 

By the way, I think circular dependencies should be avoided since naturally it means the dependency chain can be broken down.  For example, when ControllerA depends on ControllerB and vise versa, it may imply that, ControllerA and ControllerB may have a shared dependency say xxxManager.

**Comment by venkatesh3007** [comment]
@kejunxia The fragments are loaded very slowly. I didn't find any race conditions yet.

I can easily extract the shared dependencies from the inter-dependent controllers but I would like to know of any known issue which can cause more than a second delay in between the transition of fragments.

**Comment by kejunxia** [comment]
The dependency injection has some overhead due to reflections. However I did a benchmark app here to compare it with Dagger as long as there are not a lot of deeply nested injection it's fine.
https://github.com/kejunxia/AndroidMvc/tree/master/samples/benchmark

Reasons of slow loading of fragments varies. Have you tried to log elapse time of dependency injection during the fragments being loaded? I am happy to dive in to help you if that's the cause of slow fragment loading.

I encountered fragment loading lag problem but not because of dependency injection. Usually when the fragments are loaded while some animations are being played, the animations will be laggy because they are using all on UI thread. Not sure if this what you encountered.

Another direction can be investigated is how large is the model of your controllers since they will be serialized and deserialized when the fragments are recreated.

**Comment by venkatesh3007** [comment]
@kejunxia 
>  Usually when the fragments are loaded while some animations are being played, the animations will be laggy because they are using all on UI thread. Not sure if this what you encountered.

The Fragment with animations is working perfectly fine and the fragment that is taking time doesn't include any animations.

> Another direction can be investigated is how large is the model of your controllers since they will be serialized and deserialized when the fragments are recreated.

 I had encountered the problem with the size of the model in which I had database and smack (xmpp lib) objects but had removed it out of the controller model to solve the issue and now keep all our models lightweight. But recently we have injected a new component apart from the controllers. Are the attributes in the component also serialized? For example I have a DatabaseComponent which has an DatabaseManager Object in it, will that get serialized too?

**Comment by venkatesh3007** [comment]
@kejunxia -
> However I did a benchmark app here to compare it with Dagger as long as there are not a lot of deeply nested injection it's fine.

How deeply nested injection are we talking about? We have 3 levels deep nesting, at max.

**Comment by kejunxia** [comment]
Only model of Controller<MODEL> will be serialized. Default serializing implementation is gson. If it's a performance issue for heavy models, it can be customized, please refer below in which you can specify what type of object will use given implementation to serialize state.
https://github.com/kejunxia/AndroidMvc/blob/master/samples/note/android/src/main/java/com/shipdream/lib/android/mvc/samples/note/view/NoteApp.java#L43

Try to finish onViewReady(onCreate) of fragments as quick as possible. Try to move heavy stuff into asynchronous calls. Initialising DB or other IO operations could be slow.

**Comment by kejunxia** [comment]
> How deeply nested injection are we talking about? We have 3 levels deep nesting, at max. <
Sounds alright. Can you try to profile how long thing take to get injected in your slow fragments?

**Comment by venkatesh3007** [comment]
Sure. I will post the elapsed time soon.

**Comment by venkatesh3007** [comment]
@kejunxia 
Here is the code I have written to log the elapsed time in a slow Fragment. 
```
   @Override
   public void onCreate(Bundle savedInstanceState) {
       ts = System.currentTimeMillis();
       super.onCreate(savedInstanceState);
       Log.d(TAG, "Injection Elapsed Time " + (System.currentTimeMillis() - ts));
   }
```
Elapsed time varies from 1672ms to 1917ms.

**Comment by kejunxia** [comment]
That's indeed slow. Is this a direct child class of MvcFragment?

Is there any heavy lifting stuff in the onConstruct callback of the
injected controller(s)? Please try to profile the more detailed chunk you
think to cause the performance hit to narrow down.

**Comment by venkatesh3007** [comment]
yes that's a direct child class of MVCFragment.

**Comment by kejunxia** [comment]
Since onCreate does multiple things, register event bus, injection, and restoring state. I need to more break down to investigate the issue. 
https://github.com/kejunxia/AndroidMvc/blob/master/library/android-mvc/src/main/java/com/shipdream/lib/android/mvc/view/MvcFragment.java#L197

Does the fragment has a lot of onEvent callbacks? 
Is the fragment slow on fresh load or restoring state?

If you can provide a mini project simulating the problem it will be helpful.

**Comment by venkatesh3007** [comment]
@kejunxia - 

> - Does the fragment has a lot of onEvent callbacks?

Yes, the slow fragment has 16 onEvent callbacks. Even I suspect this to one of the cause in the latency.

Give me an hour or so, I will try to recreate the issue in a new project with a lot of onEvent callbacks.

**Comment by venkatesh3007** [comment]
> Controllers now are supposed to have one-to-one relationship with a view

Please elaborate the one-to-one relationship between a view and a controller.

**Comment by kejunxia** [comment]
That means, every view has its own controller. For example, FragmentA has ControllerA, FragmentB has ControllerB. If FragmentB needs access something like current loggedUser instance which managed by ControllerA, then consider to break it out as a UserManager and injected into ControllerA and ControllerB.

Controllers are now more like ViewModel of a View which represents the state of a View and manages it.

**Comment by kejunxia** [comment]
Can you try if fragment load time is reduced after onEvent methods are removed

**Comment by venkatesh3007** [comment]
I will try doing that.

 And also I am using 12 controllers in the Fragment, there is no one to one relationship as you have explained in the changelog. Do you think that can also be a potential cause for the latency.?

**Comment by kejunxia** [comment]
Maybe. 12 controllers may be an injection burden. If they have cross reference, the dependency graph size may multiples quickly. e.g. 12 controllers have averagely 3 injectable fields and each field also has 2 injectable fields. Then the total is 12 x 3 x 2 which is 96 fields need to be injected. Just an extreme example.

What do your controllers do? Controlling a widget like textview/imageview/etc or controlling the whole fragment as a page?

I will update the documents to reflect the change later. Currently the documents are out of date.

**Comment by venkatesh3007** [comment]
Controllers in my app are individual app based components. For example :- A fragment needs to fetch the configuration first and then get the content depending on the URLs specified in the response data. For the above case - We have two controllers - One to fetch the configuration and the other one to fetch content based on the response. A controller contains all the functions required for a particular component.

**Comment by poojadeshpande91** [comment]
Would you please explain how to add this library locally in android studio as I want to add some Logs to check the delay in injection of controllers.

**Comment by kejunxia** [comment]
Copy the projects into your project, then add a source project dependency to your android project the by 

compile project(':[your lib path]:android-mvc')

If you have you controllers as a separate java moulde add below 
compile project(':[your lib path]:android-mvc-controller')

And don't forget to include modules in your settings.gradle

Also refer the sample projects

**Comment by venkatesh3007** [comment]
@kejunxia  - There are 149 injections in total in the slow fragment.

**Comment by kejunxia** [comment]
That's a considerable amount may slow down. Try to avoid circular depebdency. Though the framework can handle it but dectecting it still takes time to analyze and transverse those unnecessary circular reference graph.

In your previous use case, I think you can have a UrlManager manages base urls. Then each fragment has one conttoller just to control the fragment(view). Controllers need to acess the dynamic base url have the urlmanager injected. 

So controllers won't depend on other  controllers but only managers which are a lower layer below controllers shared by controllers. In this way, there would be no circular reference. Dependent chain may be a little simpler and clearer.

**Comment by venkatesh3007** [comment]
The app has 40 controllers in total and there is a lot of interdependency among them. We will extract the managers from the controller and make the dependency chain simple. 

Don't you think this should be made simpler than this?

We could have a **default controller** injected in the fragment and its implementation will be inside the controller/internal folder as it is now. Then we can access the controller in the fragment with `this.controller`. 

For a controller depending on another controller we can have container based DI. All the controller should have access to a container which contains the controllers. We can call `container.getController('controllerName')` from dependent controller to access it.

I am not sure if this can be accommodated in the current design.

**Comment by kejunxia** [comment]
My thought is a controller should be the abstraction of a view(fragment). It's the controller of the view but not data. 

Controller that controlling domain data was my original thought. And I found the flaws that is the same problem you are currently facing. Because this design doesn't split responsibilities clearly. They were only 2 layers in the app

Views
---------------------  depending on
Controllers

Because controllers are controlling domain data, it's inevitable controllers will reference other controllers. And then it will become messy quickly.

My current thought is view is abstracted by a controller+model. So views and controllers are one to one relation. Controller is the controller of a view state not domain data. When controllers need to share some logic/data. They consult managers. For example, UserManager that manages currently logged in user.

Another layer is service layer. Service abstract data access, say, in a controller it wants to show user's name on a view. It asks the UserManager, then UserManager access a UserService to get user data from database/server api/local storage/memory and etc. UserManager doesn't know where the data is from which is hidden by services. Which makes them easy to be mocked in testings. Or even a controller can access a service directly if the service data is only used by the controller. Otherwise resort to a shared manager.

So now the layers would be like this. Then there will be no messy and circular dependency. Say there 3 views, and 3 controllers. ViewA and ViewB need to interact with user data so their controller ControllerA, ControllerB share User manager which access user data by userService. ViewC's controller only need to place order, so it directly has an injected service for ordering.

Hope this graph helps. 

---ViewA--------------ViewB------------- ViewC
------|--------------------|---------------------|--------------- View layer
ControllerA------ControllerB-------ControllerC
------|--------------------|---------------------|--------------- Controller layer
----- \------------------/-----------------------|
---------------|-------------------------------  |
-------UserManager -----------------------|---------------- Manager layer
---------------|---------------------------------|
-----User Service-------------------OrderService-------------- Service layer
---------------|---------------------------------------------------- Data layer
         Database / Clound / Local Preference / Files etc


In addition, you don't have to inject object by fields. You can use 
[MvcGraph#reference(Class, Annotation)](https://github.com/kejunxia/AndroidMvc/blob/master/library/android-mvc-controller/src/main/java/com/shipdream/lib/android/mvc/MvcGraph.java#L194) to get an instance. Don't forgot to deference it if it has a state since otherwise it's state will be serialized in onSaveInstance even it's not used by any objects. Or if you want to auto deference it use [MvcGraph#use(Class, Annotation, Consumer)](https://github.com/kejunxia/AndroidMvc/blob/master/library/android-mvc-controller/src/main/java/com/shipdream/lib/android/mvc/MvcGraph.java#L334)

**Comment by kejunxia** [comment]
@venkatesh3007 just updated the document on the github home page
https://github.com/kejunxia/AndroidMvc

**Comment by venkatesh3007** [comment]
@kejunxia - Moved all the shared stuffs into managers. The latency issue is resolved in almost all the injections. However a couple of injections still take 100-150ms. I am looking into them. Thank you so much for your support. 

I think this library can be really helpful to implement the concept of "atoms" for enabling Android Instant Apps.

Would love to discuss and contribute for further development of this project.

**Comment by kejunxia** [comment]
Happy to hear your project gets faster. Latency was expected by me because of the reflections. That's why I did a benchmark app to monitor the performance. Is your project very performance critical? I feel like upt to 100ms is ok for my projects as long as it's not in a loop. 

Can you give me a little more details about "atoms" and instant apps you mentioned above? Not sure what you meant.

**Comment by venkatesh3007** [comment]
Go through this - https://developer.android.com/topic/instant-apps/index.html
