### ISSUE TITLE
Duplicate AppDelegateController inside the MVVM Sample

### ISSUE THREAD

**Issue by BenedictP** [kejunxia/AndroidMvc#60]
Inside the MVVM Sample the class "AppDelegateController" is contained in the mobile module and in the core module. I'm a little bit confused. Could someone help me why this is necessary?

https://github.com/kejunxia/AndroidMvc/blob/master/samples/simple-mvvm/mobile/src/main/java/com/shipdream/lib/android/mvc/samples/simple/mvvm/controller/AppDelegateController.java

https://github.com/kejunxia/AndroidMvc/blob/master/samples/simple-mvvm/core/src/main/java/com/shipdream/lib/android/mvc/samples/simple/mvvm/controller/AppDelegateController.java

**Comment by kejunxia** [comment]
Thanks for pointing it out. The "core" module is unused in the mvvm sample. It was there by mistake. Please ignore the it. I have updated the master branching in which the core module is deleted.

The mvvm sample doesn't divide the app into two modules is because Android Data Binding library is coupled with Android SDK. e.g. @Bindable is in Android SDK instead of being in a stand alone library. If mvvm is purely based on event bus pattern. Then the core module in plain java is still doable. Or if the android data binding lib can be depended as a plain java lib later the "core" functions can be split into plain java module like the mvp sample

**Comment by BenedictP** [comment]
Ok thanks!
