### ISSUE TITLE
Crash with ObservableList property in model

### ISSUE THREAD

**Issue by BenedictP** [kejunxia/AndroidMvc#61]
When my Model from a controller contains a ObservableList I get an java.lang.RuntimeException: Unable to start activity.
Full stacktrace: https://gist.github.com/BenedictP/e70e8925e3f5c0e1d6a2084e855edf6a

**Comment by kejunxia** [comment]
It's because the framework currently uses gson to save and restore model and gson can't  deserialise ObservableArrayList properly but deserialise it as an ArrayList. An workaround using a normal List/ArrayList in the model and insert all its items into an ObservableArrayList as a field of the controller when the controller is instantiated.
