### ISSUE TITLE
onSaveInstanceState(Bundle outState) not called when navigate to another Fragment

### ISSUE THREAD

**Issue by IbrahimDisouki** [kejunxia/AndroidMvc#71]
Hi kejunxia,
I need to call onSaveInstanceState(Bundle outState) method when i navigate to another fragment so i can store data and restore it when user click back. Now i have to reload data from server each time user navigate back to Fragment.

**Comment by kejunxia** [comment]
The issue could be caused by a come and go bug reported for a long time in here 
https://issuetracker.google.com/issues/37122334
and here
https://issuetracker.google.com/issues/37000979

In earlier version of AndroidMvc there was a hack to work around the Android support library issue above. And then the issue was fixed, but reintroduced again. Hope the issue will be fixed in future support library.

Solution
Try downgrade the Android support lib to 25.0.1 and earlier AndroidMvc lib
